title: My writeups blog
timezone: Europe/Rome
lang: en-US
baseurl: /blog

# Build settings
future: true
incremental: false
strict_front_matter: true
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'

plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed
